name: Send Email on Branch Change

on:
  push:
    branches:
      - '*'
jobs:
  send_email:
    runs-on: ubuntu-latest
    name: Send mail
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{ secrets.MAIL_CONNECTION }}
        server_address: smtp.gmail.com
        server_port: 465
        subject: Github Actions job result
        to: rxmagics@gmail.com
        from: Luke Skywalker # <user@example.com>
        body: Build job of ${{ github.repository }} completed successfully!
